Code optimization, bit refactoring and standardization
pmusolino/Wormholy pull request #85
Opened 2020-04-28 14:05 UTC by SagarSDagdu

1. Added an extensions file so that all extensions are at a single place.
2. Removed bundle subclass and other unused subclasses as most of them contained only extensions
3. Added storyboard **extension**.
4. Segregated RequestsVC code.
5. Fixed a typo in **changeTextColor** method name
6. Added filenameSuffix method to the enum so that it stays relevant to the reader.

2020-07-13 10:22 UTC, ozgur commented on Sources/Subclasses/WHNavigationController.swift
> +        customiseApperance()
typo: `customiseAppearance`

2020-08-19 20:05 UTC, Myrenkar requested changes
It's a bit more readable, but still messy.

2020-08-19 20:05 UTC, Myrenkar commented on Sources/UI/RequestDetailViewController.swift
> +        tableView.register(UINib(nibName: "TextTableViewCell", bundle: Bundle.wormholyBundle), forCellReuseIdentifier: "TextTableViewCell")
If you create static extension then you could use 
```swift
tableView.register(UINib(nibName: "TextTableViewCell", bundle: .wormholyBundle), forCellReuseIdentifier: "TextTableViewCell")
```

2020-08-19 20:05 UTC, Myrenkar commented on Sources/UI/RequestsViewController.swift
> +        collectionView?.register(UINib(nibName: String(describing: RequestCell.self), bundle: Bundle.wormholyBundle), forCellWithReuseIdentifier: requestCellIdentifier)
Same here with 
```swift
        collectionView?.register(UINib(nibName: String(describing: RequestCell.self), bundle: .wormholyBundle), forCellWithReuseIdentifier: requestCellIdentifier)
Write
```

2020-08-19 20:05 UTC, Myrenkar commented on Sources/UI/RequestsViewController.swift
> +    @objc private func openActionSheet(_ sender: UIBarButtonItem){
Formatting, space after

```swift
(_ sender: UIBarButtonItem)
```

2020-08-19 20:05 UTC, Myrenkar commented on Sources/Extensions.swift
> +extension Bundle {
Do you think it makes more readable to place all extensions into single file rather than to split extensions by class?

2020-12-08 17:21 UTC, emrcftci commented on Sources/Subclasses/WHNavigationController.swift
> +    override func didReceiveMemoryWarning() {
please remove this redundant function

2021-11-01 18:36 UTC, pmusolino commented
Because of the latest changes and because we removed some of the classes, I'm going to close this PR, but feel free to re-open it with the changes on the new classes.

2021-11-01 18:36 UTC, closed without merging